# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Brian Meek
title: Software Developer
email: bwmeek@brianwmeek.com
website: brianwmeek.com

# Social links
twitter_username: bwmeek
github_username:  bwdev
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: themeekisonfire
linkedin_username: brian-meek-6a840010
pinterest_username: Bwmeek
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/avatar.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brian and I'm a Software Developer. I enjoy designing systems on the front end as well as the back end. I aim to deliver value to my customers through meaningful contributions in software design and development. I have experience building products that meet high standards in web design, user experience, quality, and speed.

  Some of the technologies I enjoy working with include: 
  <mark>.NET</mark>  <mark>Angular 2+</mark>  <mark>Rails</mark>  <mark>Node.js</mark>  <mark>JavaScript</mark>  <mark>TypeScript</mark>  <mark>PowerShell</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software development some of my other interests and hobbies are:
   - Fishing
   - Music
   - Camping

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
